---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.builtin
  vars_files:
    - group_vars/main.yml
  vars:
    title: "{{ title }}"
    message: "{{ message }}"
    details: "{{ details }}"
    status: "{{ status }}"
    url: "{{ url }}"
    notify_image: '{{ status_image[status | default("this key does not exist in the dict")] | default("") }}'
  roles:
    - role: notify