version: "3"

vars:
  DOCKER_IMAGE_BUILDER: builder

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task --help
      - task --list

  notify:teams:
    desc: "Envia uma notificação a um canal do teams"
    cmds:
      - >
        ansible-playbook playbook.yml \
          -i "inventory/inventory" \
          --extra-vars='title="{{.TITLE}}" \
            message="{{.MESSAGE}}" \
            details="{{.DETAILS}}" \
            status={{.STATUS}} \
            url={{.URL}}'
