trigger: none

stages:
  - stage: deploy
    displayName: deploy develop
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: develop
        environment: deploy-development
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1
                - bash: |
                    ansible-playbook playbook.yml \
                      -i "inventory/inventory" \
                      --extra-vars='title="Deploy notification" \
                        message="Start deploy" \
                        details="Start deploy for azure repo" \
                        status="init" \
                        url="https://dev.azure.com/$(System.TeamFoundationCollectionName)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"' \
                      -vvv
                  displayName: "task notify:teams"

            on:
              success:
                steps:
                  - checkout: self
                    fetchDepth: 1
                  - bash: |
                      ansible-playbook playbook.yml \
                        -i "inventory/inventory" \
                        --extra-vars='title="Deploy notification" \
                          message="Success deploy" \
                          details="Success deploy for azure repo" \
                          status="success" \
                          url="https://dev.azure.com/$(System.TeamFoundationCollectionName)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"' \
                        -vvv
                    displayName: "task notify:teams"

              failure:
                steps:
                  - checkout: self
                    fetchDepth: 1
                  - bash: |
                      ansible-playbook playbook.yml \
                        -i "inventory/inventory" \
                        --extra-vars='title="Deploy notification" \
                          message="Failure deploy" \
                          details="Failure deploy for azure repo" \
                          status="failure" \
                          url="https://dev.azure.com/$(System.TeamFoundationCollectionName)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"' \
                        -vvv
                    displayName: "task notify:teams"
